### ISSUE TITLE
Minor optimization in hmxACA.m

### ISSUE THREAD

**Issue by mancellin** [matthieuaussal/gypsilab#1]
Hi,

First, thank you for your great work and for sharing it!
I've been closely looking at your implementation of the ACA and have taken some inspiration for my own version.
I noticed something in the following code:
```
u   = B(:,n)'*B(:,1:n-1);
v   = A(:,n)'*A(:,1:n-1);
AB  = v*u.';
u   = B(:,1:n-1)'*B(:,n);
v   = A(:,1:n-1)'*A(:,n);
BA  = u.'*v;
Rn2 = Rn2 + AB + BA + An2*Bn2;
```
Correct me if I'm wrong, but `AB` and `BA` are the same (up to complex conjugation).
I believe you could save a couple of multiplications by doing:
```
u   = B(:,n)'*B(:,1:n-1);
v   = A(:,n)'*A(:,1:n-1);
AB  = v*u.';
Rn2 = Rn2 + 2*real(AB) + An2*Bn2;
```

Also, for the complex-valued case, I would have added a `real` on `An2` and `Bn2`. It does not bother Matlab to handle complex numbers in `sqrt(An2)*sqrt(Bn2) > tol*sqrt(Rn2)`, but I'm not sure if this is a good practice, even when the imaginary part is just zero or a rounding error.

Cheers,

**Comment by matthieuaussal** [comment]
Thank you for this proposal. Indeed, many cases require compression on complex numbers, which explains this formalism. I will take a closer look at your suggestion, checking that the final accuracy of the ACA compressor remains.

Best regards,

M. Aussal

**Comment by matthieuaussal** [comment]
It's done and it works, thank you!

M. Aussal
